name: Lint HTML

on: [push, pull_request]

jobs:
  html-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run HTMLHint via npx
        run: npx --yes htmlhint "**/*.html"
