name: Hola UTP

on: 
  push: 
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar un mensaje
        run: echo "Hola estudiantes de la UTP, este es un mensaje de prueba"
      - name: Te envio la fecha
        run: date        
