name: Say hello

on: 
  push: 
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the menssage 
        run: echo "Hola Alexander"
<<<<<<< HEAD

      - name: Dime la fecha
        run: date        
=======
>>>>>>> 9d6b29359dd596e44567b44a07b44e8ffba9779c

