name: Show Commit Info

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  show-commit-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show branch name
        run: |
          if [ -n "$GITHUB_HEAD_REF" ]; then
            echo "Ejecutando en la rama PR: $GITHUB_HEAD_REF"
          else
            echo "Ejecutando en la rama push: ${GITHUB_REF#refs/heads/}"
          fi
        env:
          GITHUB_REF: ${{ github.ref }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}

      - name: Show last 5 commits
        run: |
          echo "===== Últimos 5 commits ====="
          git log -5 --pretty=format:"%h | %an | %ae | %ad | %s" --date=local

      - name: Mostrar mensaje personalizado
        run: echo "¡GitHub Actions funcionando perfectamente! 🚀"
