name: Show Commit Info

on: [push, pull_request]

jobs:
  show-commit-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Show Git Info
        run: |
          echo "Últimos 5 commits:"
          git log -5 --pretty=format:"%h | %an | %ae | %ad | %s" --date=local
